export const USER_ROLES = Object.freeze({
  AGENT: 'AGENT',
  CLAIMS_MANAGER: 'CLAIMS_MANAGER',
  SUPERVISOR: 'SUPERVISOR',
  ADMIN: 'ADMIN'
});

export const USER_ROLE_LABELS = Object.freeze({
  [USER_ROLES.AGENT]: 'Agent',
  [USER_ROLES.CLAIMS_MANAGER]: 'Claims Manager',
  [USER_ROLES.SUPERVISOR]: 'Supervisor',
  [USER_ROLES.ADMIN]: 'Admin'
});

export const DOSSIER_STATUSES = Object.freeze({
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  UNDER_REVIEW: 'UNDER_REVIEW',
  IN_ESCALATION: 'IN_ESCALATION',
  AWAITING_COMPLEMENT: 'AWAITING_COMPLEMENT',
  PROCESSED: 'PROCESSED'
});

export const DOSSIER_STATUS_LABELS = Object.freeze({
  [DOSSIER_STATUSES.RECEIVED]: 'Received',
  [DOSSIER_STATUSES.IN_PROGRESS]: 'In Progress',
  [DOSSIER_STATUSES.UNDER_REVIEW]: 'Under Review',
  [DOSSIER_STATUSES.IN_ESCALATION]: 'In Escalation',
  [DOSSIER_STATUSES.AWAITING_COMPLEMENT]: 'Awaiting Complement',
  [DOSSIER_STATUSES.PROCESSED]: 'Processed'
});
